### ISSUE TITLE
directory firmware/trezour should read firmware/trezor

### ISSUE THREAD

**Issue by prusnak** [monero-project/kastelo#12]
$title says it all

**Comment by michaesc** [comment]
This is taking so long to resolve because we may completely delete the directory in question if it's not in use.

For months we've used word plays like ledgour, trezour, monezor, and similar. The 'our' in these names is not a typo but rather refers to 'our adaptation of ...'

If you understand this but still think it's better to rename to firmware/trezor just say so and the change will be forthcoming.

Thanks for taking the time to look around our repository, by the way. Very nice of you.

**Comment by prusnak** [comment]
I did not realize it is a wordplay, okay then, closing :-)
