### ISSUE TITLE
Enclosures needed?

### ISSUE THREAD

**Issue by morriswinkler** [monero-project/kastelo#26]
I was working on an enclosure for the monezor.

Regarding the rather long list of hardware, what priorities do they have?
I just do want to prevent working on the wrong one?
 
```
antennas	
breakneck
clonebox	
clonedime
clonekeep	
cloneledg	
clonetrez	
fpgalogic	
monezor	
utilities	
```

**Comment by michaesc** [comment]
Our bug reports (mistakenly called issuances by Github) are found on:

https://taiga.getmonero.org/project/michael-rfc-hwallet-1-implementation/issues/

...to which this GitHub area will automatically refer, once it's properly configured.

Hi Morris,

Since your question relates to a already documented task, please see task 161 for the answer to your question:

https://taiga.getmonero.org/project/michael-rfc-hwallet-1-implementation/task/161/

Thanks!
Michael

**Comment by morriswinkler** [comment]
Just to sum up:

```
antennas	
breakneck **
clonebox	
clonedime
clonekeep	
cloneledg	
clonetrez	
fpgalogic	
monezor	**
utilities	
```
** enclosures needed
